server:
  port: 9000
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
  # cloud:
  #   gateway:
  #     routes:
  #       - id: user-authentication-service
  #         uri: http://192.168.1.7:8086
  #         predicates:
  #           - Path=/api/auth/**

  #       - id: user-movie-service
  #         uri: http://192.168.1.7:8082
  #         predicates:
  #           - Path=/api/movies/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost




